//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _IDENavigableItemFilterMatcher : NSObject
{
}

- (BOOL)_matchesRepresentedObject:(id)arg1;
- (BOOL)_matchesNavigableItem:(id)arg1;

@end

