//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class IDEEditor, NSButton;

@interface _IDECoverageNameTableCellView : NSTableCellView
{
    NSButton *_jumpButton;
    id _coverageItem;
    IDEEditor *_hostEditor;
}

- (void).cxx_destruct;
@property __weak IDEEditor *hostEditor; // @synthesize hostEditor=_hostEditor;
@property __weak id coverageItem; // @synthesize coverageItem=_coverageItem;
@property __weak NSButton *jumpButton; // @synthesize jumpButton=_jumpButton;
- (void)jumpToSourceCode:(id)arg1;

@end

