//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _IDETestReportActivityHelper : NSObject
{
}

+ (id)userFriendlyNameForAttachmentName:(id)arg1 UTI:(id)arg2 inActivityIdentifier:(long long)arg3;
+ (id)transitiveAttachmentsForActivity:(id)arg1;
+ (id)subitemsForActivity:(id)arg1;

@end

