//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit28IDEWorkspaceExplorableSource.h>

#import <IDEKit/DVTFilteredDataSource-Protocol.h>

@class OS_dispatch_queue;

@interface _TtC6IDEKit28IDEWorkspaceExplorableSource (IDEKit) <DVTFilteredDataSource>
- (void)filterWithFilterSession:(id)arg1;
@property(nonatomic, readonly) OS_dispatch_queue *filteringQueue;
@end

