//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit27SigningEditorViewController.h>

#import <IDEKit/IDESigningEditorCapabilityEditingItemChangeExistenceProtocol-Protocol.h>

@interface _TtC6IDEKit27SigningEditorViewController (IDEKit2) <IDESigningEditorCapabilityEditingItemChangeExistenceProtocol>
- (void)addCapabilityItemWithIdentifiers:(id)arg1;
@end

