//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTPortal/_TtC9DVTPortal27DVTPortalCertificatePurpose.h>

@interface _TtC9DVTPortal27DVTPortalCertificatePurpose (ManualDistributionSigningAddtions)
- (id)automaticSelectorIdentity;
@end

