//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@interface _TtC6IDEKit43IDEWorkspaceSourceIdentifierTypeDeclaration : _TtCs12_SwiftObject
{
}

@end

