//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit30IDETestPlansListViewController.h>

@interface _TtC6IDEKit30IDETestPlansListViewController (IDEKit)
- (void)changeDefaultTestPlanButtonPressed:(id)arg1;
- (void)jumpButtonPressed:(id)arg1;
- (void)deleteButtonPressed:(id)arg1;
- (void)addNewTestPlan:(id)arg1;
- (void)addExistingTestPlan:(id)arg1;
@end

