//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit23TrainyardViewController.h>

@interface _TtC6IDEKit23TrainyardViewController (IDEKit2)
- (BOOL)tableView:(id)arg1 doCommandBySelector:(SEL)arg2;
@end

