//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAccessibilityElement.h>

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit40IDENavigationOverlayAccessibilityElement : NSAccessibilityElement
{
}

- (id)init;
- (BOOL)accessibilityPerformPress;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;

@end

