//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit41SigningEditorConfigurationsViewController.h>

#import <IDEKit/DVTScopeBarButtonDelegate-Protocol.h>

@interface _TtC6IDEKit41SigningEditorConfigurationsViewController (IDEKit) <DVTScopeBarButtonDelegate>
- (void)didLayoutScopeBarButton:(id)arg1;
@end

