//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit37IDESourceControlFileHistoryLogRowView : NSTableRowView
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)drawSelectionInRect:(struct CGRect)arg1;
@property(nonatomic, readonly) long long interiorBackgroundStyle;

@end

