//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSFont, NSString;

@protocol DVTEmptyContentPlaceholderContainer
@property(nonatomic) BOOL hasContent;
@property(copy, nonatomic) NSFont *emptyContentFont;
@property(nonatomic) long long emptyContentStringStyle;
@property(copy, nonatomic) NSString *emptyContentSubtitle;
@property(copy, nonatomic) NSString *emptyContentString;

@optional
@property(nonatomic) BOOL followsFontAndColorTheme;
@property(copy, nonatomic) NSString *emptyContentButtonTitle;
- (void)willHideEmptyContentString;
- (void)willShowEmptyContentString;
@end

