//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class NSMutableArray;

@protocol DVTEditor <NSObject>
- (void)discardEditing;
- (BOOL)commitEditingForAction:(int)arg1 errors:(NSMutableArray *)arg2;
@end

