//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTFoundation/DVTFileDataType.h>

@interface DVTFileDataType (IDECounterpartsAdditions)
@property(readonly) BOOL isCSourceDataType;
@property(readonly) BOOL isCHeaderDataType;
@property(readonly) BOOL isSourceDataType;
@property(readonly) BOOL isSwiftSource;
@end

