//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTFilePathFieldCell, NSString;

@protocol DVTFilePathFieldCellDelegate

@optional
- (NSString *)DVTFilePathFieldCell:(DVTFilePathFieldCell *)arg1 resolvedPathForPath:(NSString *)arg2;
- (void)DVTFilePathFieldCell:(DVTFilePathFieldCell *)arg1 chooserSelectedPath:(NSString *)arg2;
@end

