//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSOutlineView.h>

@class NSEvent;

@interface IDEAbstractFindNavigatorOutlineView : NSOutlineView
{
    NSEvent *_currentKeyDownEvent;
}

- (void).cxx_destruct;
- (void)doCommandBySelector:(SEL)arg1;
- (void)dvt_expandRowAndPossiblySiblings:(id)arg1;
- (id)delegate;
- (void)keyDown:(id)arg1;
- (id)makeViewWithIdentifier:(id)arg1 owner:(id)arg2;

@end

