//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEAssistant.h>

@class NSTextView;

@interface IDEARCConversionApprovalAssistant : IDEAssistant
{
    NSTextView *_textView;
}

+ (id)keyPathsForValuesAffectingCanGoForward;
- (void).cxx_destruct;
- (void)loadView;
- (id)_messageContentsURL;
- (BOOL)canGoForward;
- (id)nextAssistantIdentifier;

@end

