//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTKit/DVTClickableLayer.h>

@class NSImage, NSString;

@interface IDEActivityActionButtonLayer : DVTClickableLayer
{
    NSString *_title;
    NSString *_actionDescription;
}

- (void).cxx_destruct;
@property(copy) NSString *actionDescription; // @synthesize actionDescription=_actionDescription;
@property(copy) NSString *title; // @synthesize title=_title;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityAttributeNames;
- (void)layerShouldShowUnclickedState;
- (void)layerShouldShowClickedState;
@property(retain) NSImage *image;
- (id)init;

@end

