//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSImage, NSString;

@protocol IDEAccountPrefsPaneAccount
@property(nonatomic, readonly) long long accountReachability;
@property(nonatomic, readonly) BOOL accountEnabled;
@property(nonatomic, readonly) NSImage *accountImage;
@property(nonatomic, readonly) NSString *accountSubTitle;
@property(nonatomic, readonly) NSString *accountTitle;
@end

