//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEBatchFindQueryTerm.h>

@interface IDEBatchFindQueryTerm (UIAdditions)
- (id)displayAttributedStringWithFont:(id)arg1;
@end

