//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEBlueprintMenuBuilder : NSObject
{
}

+ (id)blueprintMenuForBlueprintProviders:(id)arg1 blueprintEnabledBlock:(CDUnknownBlockType)arg2 target:(id)arg3 selector:(SEL)arg4;
+ (id)menuImageForImage:(id)arg1;

@end

