//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEInspectorViewController.h>

@interface IDEContainerItemInspector : IDEInspectorViewController
{
}

+ (id)keyPathsForValuesAffectingShouldChooseRelativeContainingFolderLocation;
+ (id)keyPathsForValuesAffectingShouldChooseSingleRelativeLocation;
- (BOOL)shouldChooseRelativeContainingFolderLocation;
- (void)applyRelativeLocationChoice:(id)arg1;
- (BOOL)shouldChooseSingleRelativeLocation;
- (void)renameFiles:(id)arg1;

@end

