//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, NSURL;

@protocol IDECapabilityItemLibraryAssetProtocol
@property(nonatomic, readonly) NSString *identifier;
@property(nonatomic, readonly) NSURL *imageURL;
@property(nonatomic, readonly) NSString *capabilityDescription;
@property(nonatomic, readonly) NSString *name;
@end

