//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEActivityReporter.h>

@class DVTObservingToken;

@interface IDECleanBuildFolderActivityReporter : IDEActivityReporter
{
    DVTObservingToken *_isCleaningObserver;
}

- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)initWithWorkspace:(id)arg1;
- (void)updateActivityReports;
- (id)completionSummaryStringSegments;

@end

