//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEAlertViewController.h>

@class NSTextField;

@interface IDEDialogAlertViewController : IDEAlertViewController
{
    NSTextField *alertKindLabel;
}

- (void).cxx_destruct;
@property(retain) NSTextField *alertKindLabel; // @synthesize alertKindLabel;
- (void)loadView;

@end

