//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/NSObject-Protocol.h>

@class DVTStackView_AppKitAutolayout;

@protocol IDEDebugGaugeReportContentDelegate <NSObject>
- (BOOL)hasDefaultTopSection;

@optional
- (void)addSectionsToView:(DVTStackView_AppKitAutolayout *)arg1;
@end

