//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDELaunchActionOptionViewController.h>

@class IDEScheme, NSMenu;

@interface IDEGPUDebuggerOptionsController : IDELaunchActionOptionViewController
{
    NSMenu *_menu;
    IDEScheme *_scheme;
}

+ (BOOL)availableForScheme:(id)arg1;
- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (void)loadView;
- (id)initWithScheme:(id)arg1 schemeAction:(id)arg2;

@end

