//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEIndexSymbol-Protocol.h>

@class IDEIndexCollection;
@protocol IDEIndexPropertySymbol;

@protocol IDEIndexCallableSymbol <IDEIndexSymbol>
@property(readonly, nonatomic) id <IDEIndexPropertySymbol> property;
@property(readonly, nonatomic) IDEIndexCollection *overriddenSymbols;
@end

