//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEInspectorProperty.h>

@class NSNumber;

@interface IDEInspectorEnumerationProperty : IDEInspectorProperty
{
    NSNumber *_unusedEnumerationValue;
}

+ (Class)propertyClassForPropertyDefinition:(id)arg1;
- (void).cxx_destruct;
- (long long)unusedEnumerationValue;

@end

