//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEManageCertificatesItem.h>

@class NSImage;

@interface IDEManageCertificatesItem (KitAdditions)
@property(readonly) BOOL enabled;
@property(readonly) NSImage *icon;
@end

