//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSButton;

@interface IDEManageRunContextsSheetControllerCheckButtonTableCellView : NSTableCellView
{
    NSButton *_checkButton;
}

- (void).cxx_destruct;
@property(retain) NSButton *checkButton; // @synthesize checkButton=_checkButton;

@end

