//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDEMediaLibraryDetailViewHeading : NSObject
{
    NSString *_title;
    NSString *_subtitle;
}

- (void).cxx_destruct;
@property(readonly) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly) NSString *title; // @synthesize title=_title;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2;

@end

