//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDEProvisioningUserActionSheetController : NSObject
{
}

+ (void)presentSheetForUserAction:(id)arg1 manager:(id)arg2 supportBatchActions:(BOOL)arg3 hostWindow:(id)arg4 callback:(CDUnknownBlockType)arg5;

@end

