//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDESingleFileProcessingContentProvider.h>

@interface IDEPreprocessedContentProvider : IDESingleFileProcessingContentProvider
{
}

+ (long long)buildOperationCommand;
+ (id)urlScheme;
- (void)_kickOffContentGenerationWithFilePath:(id)arg1 schemeCommand:(id)arg2;

@end

