//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEGraph.h>

@interface IDEPlotGraph : IDEGraph
{
}

- (id)attributesForGraph;
- (Class)graphClass;
- (id)initWithFrame:(struct CGRect)arg1;

@end

