//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDERunSheetPhaseModel.h>

@interface IDERunSheetPreviewPhaseModel : IDERunSheetPhaseModel
{
}

- (id)schemeCommandTitle;
- (int)schemePhaseModelCommand;
- (id)navigableItem_image;
- (Class)detailViewControllerClass;
- (id)runPhase;

@end

