//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDESourceControlTreeConflictNode.h>

@interface IDESourceControlTreeConflictNode (IDESourceControlTreeConflictNodeNavigablePropertyAdditions)
+ (id)keyPathsForValuesAffectingNavigableItem_conflictStateForUpdateOrMerge;
- (unsigned long long)navigableItem_conflictStateForUpdateOrMerge;
@end

