//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@interface IDESourceControlCredentialAbstractWindowController : NSWindowController
{
    BOOL _applyToOthers;
}

@property(readonly, nonatomic) BOOL applyToOthers; // @synthesize applyToOthers=_applyToOthers;
- (id)initWithRemoteRepository:(id)arg1 othersToOffer:(unsigned long long)arg2 sshKeyComment:(id)arg3 sshKeyFolderURL:(id)arg4 owningWindow:(id)arg5;

@end

