//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDENavigableItem.h>

@interface IDESchemeNavigable : IDENavigableItem
{
}

+ (id)iconForBuildable:(id)arg1;
+ (id)schemeTitleErrorSuffixAttributedString;
+ (id)keyPathsForValuesAffectingName;
- (id)childRepresentedObjects;
- (BOOL)isLeaf;
- (id)image;
- (id)name;
- (id)scheme;
- (id)initWithRepresentedObject:(id)arg1;

@end

