//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDETest_ActivityAttachment_Base-Protocol.h>

@class NSNumber, NSString;

@protocol IDETestReport_TestAttachment <IDETest_ActivityAttachment_Base>
@property(readonly, copy, nonatomic) NSNumber *ide_test_attachment_payloadSize;
@property(readonly, copy, nonatomic) NSString *ide_test_attachment_payload_filePath;
@property(readonly, copy, nonatomic) NSString *ide_test_activity_UTI;
@end

