//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDELaunchActionOptionViewController.h>

@class NSButton;

@interface IDEViewDebuggingOptionsViewController : IDELaunchActionOptionViewController
{
    NSButton *_enableViewDebuggingCheckBox;
}

+ (BOOL)availableForScheme:(id)arg1;
- (void).cxx_destruct;
@property __weak NSButton *enableViewDebuggingCheckBox; // @synthesize enableViewDebuggingCheckBox=_enableViewDebuggingCheckBox;
- (void)enableViewDebuggingClicked:(id)arg1;
- (void)loadView;

@end

