//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (DVTXMLArchiving)
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1 version:(id)arg2;
@end

