//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface NSWindow (IBResizingAdditions)
- (void)IDE_IB_setContentViewSizePinningTopLeft:(struct CGSize)arg1 display:(BOOL)arg2 animate:(BOOL)arg3;
- (struct CGRect)IDE_IB_contentRectForContentSizePinningToTopLeft:(struct CGSize)arg1;
@end

