//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/XCLogMessageAdapter.h>

@interface XCLogAnalyzerStepAdapter : XCLogMessageAdapter
{
}

- (id)titleForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;

@end

