//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/XCLogUnitTestAdapter.h>

@interface XCLogUnitTestWorkerAdapter : XCLogUnitTestAdapter
{
}

- (id)secondRowStringForDataNode:(id)arg1;
- (double)_baseHeightOfRowForDataNode:(id)arg1;
- (BOOL)displaysBadge;
- (id)badgeImageForDataNode:(id)arg1;
- (id)imageForDataNode:(id)arg1;

@end

