//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/_IDENavigableItemExtraInfo.h>

@class NSMapTable;

@interface _IDEContainerItemNavigableItemExtraInfo : _IDENavigableItemExtraInfo
{
    NSMapTable *_observersByModelObjectGraph;
}

- (void).cxx_destruct;
@property(readonly) NSMapTable *_observersByModelObjectGraph; // @synthesize _observersByModelObjectGraph;
- (void)configureObservingForModelObjectGraph:(id)arg1;
- (void)processModelObjectGraphNotification:(id)arg1;
- (id)init;

@end

