//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTToolbarViewController.h>

@class IDEActivityView;

@interface _IDEActivityViewToolbarViewController : DVTToolbarViewController
{
    IDEActivityView *_activityView;
}

- (void).cxx_destruct;
- (void)primitiveInvalidate;
- (id)initWithToolbarItemIdentifier:(id)arg1 window:(id)arg2;

@end

