//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface _IDESwipeAnimationHostView : NSView
{
}

- (void)updateLayer;
- (BOOL)wantsUpdateLayer;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (id)hitTest:(struct CGPoint)arg1;

@end

