//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class NSButton, NSProgressIndicator;

@interface _IDETestReportAttachmentCellView : NSTableCellView
{
    NSButton *_quickLookButton;
    NSProgressIndicator *_loadingProgress;
}

- (void).cxx_destruct;
@property __weak NSProgressIndicator *loadingProgress; // @synthesize loadingProgress=_loadingProgress;
@property __weak NSButton *quickLookButton; // @synthesize quickLookButton=_quickLookButton;
- (void)stopLoading;
- (void)startLoading;
- (void)setBackgroundStyle:(long long)arg1;
- (void)awakeFromNib;

@end

