//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTViewControllerToolbarItem.h>

@interface _IDEActivityViewControllerToolbarItem : DVTViewControllerToolbarItem
{
}

- (void)configureForDisplayMode:(unsigned long long)arg1 andSizeMode:(unsigned long long)arg2;
- (id)activityToolbarViewController;

@end

