//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSButton, NSTrackingArea;

@interface _IDETestReportJumpButtonTrackingView : NSView
{
    NSTrackingArea *_trackingArea;
    NSButton *_jumpButton;
}

- (void).cxx_destruct;
@property __weak NSButton *jumpButton; // @synthesize jumpButton=_jumpButton;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;

@end

