//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

#import <IDEKit/IDEStructureEditingItem-Protocol.h>

@class MISSING_TYPE;

@interface _TtCC6IDEKit21IDEWorkspaceNavigator29StructureEditingContainerItem : _TtCs12_SwiftObject <IDEStructureEditingItem>
{
    MISSING_TYPE *containerItem;
    MISSING_TYPE *parentContainerItem;
}

- (id)parentStructureEditingItem;
- (unsigned long long)indexUnderParent;
- (id)representedContainerItem;

@end

