//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC6IDEKit38IDENavigationOverlayEditorAreaDelegate : NSObject
{
    MISSING_TYPE *topLevelSplitContainer;
}

- (void).cxx_destruct;
- (id)init;
- (id)navigationOverlay:(id)arg1 nextTargetInDirection:(long long)arg2 from:(id)arg3 candidateTargets:(id)arg4 parentWindow:(id)arg5 fallbackDelegate:(id)arg6 considerInsertionTargets:(BOOL)arg7;
- (id)initWithMultiSplit:(id)arg1;

@end

