//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/_TtC6IDEKit30IDETestPlansListViewController.h>

@interface _TtC6IDEKit30IDETestPlansListViewController (IDEKit1)
- (long long)numberOfRowsInTableView:(id)arg1;
@end

