//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class MISSING_TYPE, NSButton;

__attribute__((visibility("hidden")))
@interface _TtC6IDEKit26IDEDefaultTestPlanCellView : NSTableCellView
{
    MISSING_TYPE *radioButton;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSButton *radioButton; // @synthesize radioButton;

@end

