//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@class MISSING_TYPE;

@interface _TtC6IDEKit19TrainyardLabelField : NSTextField
{
    MISSING_TYPE *imageView;
}

+ (void)setCellClass:(Class)arg1;
+ (Class)cellClass;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) BOOL expandIcon;

@end

