//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s6DVTKit24DVTNavigationPopoverItemCN.h"

@class MISSING_TYPE;

@interface _TtC6IDEKit39IDESourceControlLogItemPopoverBlameItem : _$s6DVTKit24DVTNavigationPopoverItemCN
{
    MISSING_TYPE *logItem;
    MISSING_TYPE *subviewController;
    MISSING_TYPE *viewController;
}

- (void).cxx_destruct;

@end

