//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import "_$s6DVTKit24DVTNavigationPopoverItemCN.h"

@interface _TtC6IDEKit48IDESourceControlLogItemPopoverOpenComparisonItem : _$s6DVTKit24DVTNavigationPopoverItemCN
{
}

- (void).cxx_destruct;

@end

