//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class MISSING_TYPE, NSImageView, NSTextField;

@interface _TtC6IDEKit32IDEAccountPrefsPaneTableCellView : NSTableCellView
{
    MISSING_TYPE *statusImageView;
    MISSING_TYPE *subtitleTextField;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) NSTextField *subtitleTextField; // @synthesize subtitleTextField;
@property(nonatomic, retain) NSImageView *statusImageView; // @synthesize statusImageView;

@end

