//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IDEExplorableJumpBarController, _TtC16DVTExplorableKit23DVTExplorableIdentifier;

@protocol _TtP6IDEKit38IDEExplorableJumpBarControllerDelegate_
- (void)jumpBarController:(IDEExplorableJumpBarController *)arg1 userDidSelectIdentifier:(_TtC16DVTExplorableKit23DVTExplorableIdentifier *)arg2;

@optional
- (BOOL)wantsRootLineageTrimForJumpBarController:(IDEExplorableJumpBarController *)arg1;
@end

