//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class DVTSourceControlRepository, NSString;

@protocol _TtP6IDEKit37IDESourceControlAuthenticationContext_
@property(nonatomic, readonly) NSString *primaryButtonTitle;
- (BOOL)containsWorkingCopyForRepository:(DVTSourceControlRepository *)arg1;
@end

