//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableView.h>

@interface IDEAppChooserTableView : NSTableView
{
}

- (BOOL)_shouldUseSecondaryHighlightColor;
- (id)makeViewWithIdentifier:(id)arg1 owner:(id)arg2;

@end

