//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDEBuildIssueProvider.h>

@interface IDEBuildIssueProvider (IDEKitAdditions)
- (id)imageForIssue:(id)arg1 ofSize:(unsigned long long)arg2;
@end

