//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IDEContainer, IDEWorkspace, NSOperationQueue, NSSet;

@protocol IDEContainerUnlockingDelegate
- (void)container:(IDEContainer *)arg1 attemptToUnlockItems:(NSSet *)arg2 workspace:(IDEWorkspace *)arg3 completionQueue:(NSOperationQueue *)arg4 completionBlock:(void (^)(BOOL, NSError *))arg5;
@end

