//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSSortDescriptor.h>

@class NSString;

@interface IDECodeModuleDefaultSortDescriptor : NSSortDescriptor
{
    NSString *_executableName;
}

- (void).cxx_destruct;
- (long long)compareObject:(id)arg1 toObject:(id)arg2;
- (id)initWithExecutableURL:(id)arg1;

@end

