//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEGraphDelegate-Protocol.h>

@class IDEEnergyAdditionGuidance, NSArray, NSColor;

@protocol IDEEnergyAnnotatedBarGraphDelegate <IDEGraphDelegate>
- (NSArray *)categoryTitles;

@optional
- (NSColor *)colorForGuidance:(IDEEnergyAdditionGuidance *)arg1;
@end

