//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSplitView.h>

@class NSColor;

@interface IDEEditorSplitView : NSSplitView
{
    NSColor *_dividerColor;
    double _dividerThickness;
}

- (void).cxx_destruct;
@property double dividerThickness; // @synthesize dividerThickness=_dividerThickness;
- (void)setDividerStyle:(long long)arg1;
- (long long)dividerStyle;
- (id)dividerColor;
- (void)viewDidChangeEffectiveAppearance;
- (BOOL)wantsUpdateLayer;

@end

