//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IDEBatchFindQuerySpecification, IDEFindNavigatorQueryParametersController, NSString;

@protocol IDEFindNavigatorQueryParametersControllerDelegate
- (void)queryParametersController:(IDEFindNavigatorQueryParametersController *)arg1 replaceAllResultsWithText:(NSString *)arg2;
- (void)queryParametersController:(IDEFindNavigatorQueryParametersController *)arg1 replaceSelectedResultsWithText:(NSString *)arg2;
- (void)queryParametersControllerCancelQuery:(IDEFindNavigatorQueryParametersController *)arg1;
- (void)queryParametersController:(IDEFindNavigatorQueryParametersController *)arg1 initiateQueryFromSpecification:(IDEBatchFindQuerySpecification *)arg2;
- (void)queryParametersControllerDidChangeExportedUserInterfaceState:(IDEFindNavigatorQueryParametersController *)arg1;
@end

