//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEImageMediaResource.h>

@interface IDEIconSetMediaResource : IDEImageMediaResource
{
}

+ (id)generateContentWithContext:(id)arg1;
+ (id)generateIconWithContext:(id)arg1;
- (id)captureContextOnMainThreadBeforeGeneratingContent;
- (id)captureContextOnMainThreadBeforeGeneratingIcon;

@end

