//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEFileNavigableItem.h>

@interface IDEIndexGeniusResultNavigableItem : IDEFileNavigableItem
{
}

- (id)fileURL;
- (id)contentDocumentLocation;
- (id)name;
- (id)documentType;
- (id)image;
- (id)_geniusResult;

@end

