//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol IDEInitialization
+ (BOOL)ide_initializeWithOptions:(unsigned long long)arg1 error:(id *)arg2;
@end

