//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/DVTInvalidation-Protocol.h>

@class IDEBuildParameters, IDEWorkspace, NSObject;
@protocol IDELocalizationWorkProgress;

@protocol IDELocalizationController <DVTInvalidation>
@property(readonly) BOOL complete;
@property(readonly) NSObject<IDELocalizationWorkProgress> *worker;
- (void)cancel;
- (void)startLocalizationOperationForWorkspace:(IDEWorkspace *)arg1 buildParameters:(IDEBuildParameters *)arg2;
@end

