//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@interface IDELayoutControlView : NSView
{
    double _maxContentWidth;
    long long _alignment;
}

@property(nonatomic) long long alignment; // @synthesize alignment=_alignment;
@property(nonatomic) double maxContentWidth; // @synthesize maxContentWidth=_maxContentWidth;
- (void)_constrainChildViewWidthWithAlignment:(long long)arg1;
- (void)layout;
- (void)setFrameSize:(struct CGSize)arg1;

@end

