//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTTableCellViewStatusController.h>

@class IDENavigatorProgressStatusView;

@interface IDENavigatorProgressStatusController : DVTTableCellViewStatusController
{
    IDENavigatorProgressStatusView *_faultedView;
    long long _progress;
}

- (void).cxx_destruct;
@property(nonatomic) long long progress; // @synthesize progress=_progress;
- (id)view;
- (void)propagateState;

@end

