//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface IDENavigableItemDomainProvider : NSObject
{
}

+ (id)domainObjectsForURL:(id)arg1 forWorkspace:(id)arg2;
+ (id)domainObjectForURL:(id)arg1 forWorkspace:(id)arg2;
+ (id)domainObjectForWorkspace:(id)arg1;

@end

