//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@interface IDEOpenQuicklyAbstractTableCellView : NSTableCellView
{
}

+ (id)secondaryLabelColorForBackgroundStyle:(long long)arg1;
- (BOOL)isFlipped;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)arrangeSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

