//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol IDEProvisioningBundleIdentifierDataSource
@property(nonatomic, readonly) NSString *bundleIdentifierPlaceholder;
@property(nonatomic, readonly) BOOL isBundleIdentifierReadOnly;
@property(nonatomic, copy) NSString *bundleIdentifier;
@property(nonatomic, readonly) BOOL wantsBundleIdentifierEditingLabel;
@property(nonatomic, readonly) BOOL wantsBundleIdentifierEditing;
@end

