//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDEDebugBarContentProvider.h>

@class DVTGradientImageButton;

@interface IDEPauseResumeDebugBarContentProvider : IDEDebugBarContentProvider
{
    DVTGradientImageButton *_pauseResumeButton;
}

- (void).cxx_destruct;
@property(readonly) BOOL hasRealDebugSession;
- (void)currentDebugSessionDidChange;
- (void)currentDebugSessionStateDidChange;
- (void)_updatePauseResumeButtonBasedOnDebugSessionState;
- (void)pauseOrResume:(id)arg1;
- (id)_createPauseResumeButton;
- (id)init;

@end

