//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSAlert, NSMatrix;

@interface IDEPGOSchemeCommandAccessoryViewController : NSViewController
{
    NSMatrix *_runOrTestMatrix;
    int _selectedMatrixTag;
    NSAlert *_alert;
}

- (void).cxx_destruct;
@property __weak NSAlert *alert; // @synthesize alert=_alert;
- (void)chooseWhatToRunAction:(id)arg1;
- (void)setTestRadioButtonEnabled:(BOOL)arg1;
- (void)setRunRadioButtonEnabled:(BOOL)arg1;
@property int selectedMatrixTag;
- (void)viewDidLoad;

@end

