//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTColoredSpinner.h>

@class NSMenuItem;

@interface IDERunDestinationMenuItemColoredSpinner : DVTColoredSpinner
{
    NSMenuItem *_menuItem;
}

- (void).cxx_destruct;
@property __weak NSMenuItem *menuItem; // @synthesize menuItem=_menuItem;
- (struct CGRect)visibleRect;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;
- (BOOL)canDraw;
- (void)_timerStep:(id)arg1;

@end

