//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol IDERenameRefactoringChange
@property BOOL shouldBeApplied;
@property(retain) NSString *valueName;
@property(readonly) NSString *originalValueName;
@property(readonly) NSString *keyName;
@property(readonly) NSString *categoryName;
@end

