//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindowController.h>

@interface IDESourceControlRepositoryCredentialAbstractWindowController : NSWindowController
{
}

- (void)beginWithWindow:(id)arg1 remoteRepository:(id)arg2 hostedAccount:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;

@end

