//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSString;

@protocol IDESigningEditorConfigurationManagerProtocol
@property(nonatomic, readonly) NSArray *configurations;
@property(nonatomic, readonly) NSString *targetName;
@property(nonatomic, readonly) NSString *projectName;
@end

