//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDESchemeOptionMenuController.h>

@interface IDESimulateLocationMenuController : IDESchemeOptionMenuController
{
}

+ (id)fileExtension;
+ (id)uti;
+ (id)defaultItems;
+ (id)_itemForFileReference:(id)arg1 inWorkspace:(id)arg2;
- (id)doNothingItemRepresentedObject;
- (id)doNothingItemTitle;
- (id)menuTitle;
- (id)init;

@end

