//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface IDESourceControlNonEmptyTextField : NSTextField
{
    BOOL _containsNonEmptyMessage;
}

@property(readonly) BOOL containsNonEmptyMessage; // @synthesize containsNonEmptyMessage=_containsNonEmptyMessage;
- (void)textDidChange:(id)arg1;
- (BOOL)_computeContainsNonEmptyMessage;

@end

