//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEFoundation/IDESourceKitCompletionItem.h>

@interface IDESourceKitCompletionItem (IDEKitExtensions)
- (unsigned long long)priorityComparatorKind;
- (long long)priorityBucket;
- (void)infoViewControllerWithWidth:(double)arg1 context:(id)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)icon;
@end

