//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <IDEKit/IDETestObserver-Protocol.h>

@class NSSet;

@protocol IDETestsInFileObserver <IDETestObserver>

@optional
- (void)testLocationsInFileUpdated:(NSSet *)arg1;
- (void)testsInFileUpdated:(NSSet *)arg1;
@end

