//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class IDESchemeActionsInvocationRecord, NSString;

@protocol IDETestReportPackagedGeniusResultDocumentRequirements
@property(readonly, nonatomic) IDESchemeActionsInvocationRecord *invocationRecord;
@property(readonly, nonatomic) NSString *uniqueIdentifier;
@property(readonly, nonatomic) NSString *onDiskPath;
@end

