//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <DVTUserInterfaceKit/DVTOutlineView.h>

@interface IDEVariablesViewOutlineView : DVTOutlineView
{
}

- (void)drawRow:(long long)arg1 clipRect:(struct CGRect)arg2;
- (void)_yellowHighlightRow:(long long)arg1;
- (void)endUpdates;
- (void)reloadItem:(id)arg1 reloadChildren:(BOOL)arg2;
- (void)reloadData;
- (void)viewDidUnhide;
- (void)viewDidHide;

@end

