//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Apr  3 2020 20:00:10).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSString;

@interface NSViewController (IDEKit)
@property(nonatomic, readonly) NSString *navigationOverlayTargetAccessibilityTitle;
@property(nonatomic, readonly) BOOL wantsHighlightEdgeAdornments;
@property(nonatomic, readonly) double highlightFrameBorderWidth;
@property(nonatomic, readonly) double highlightFrameCornerRadius;
- (struct CGRect)hitTestFrameInWindow:(id)arg1;
- (struct CGRect)highlightFrameInWindow:(id)arg1;
@end

